name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Login to DockerHub
      run: |
          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "venupj" --password-stdin 
        
    - name: Push to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
         dockerfile: ./Dockerfile
         registry: docker.io
         image: venupj/micro-sock
         
         
         
